### ISSUE TITLE
secondary development problem

### ISSUE THREAD

**Issue by CCBest2022** [MaisJamal/carla_apollo_bridge#11]
**secondary development problem**
  I need to set up a simple rear-end collision warning scene. 
  First, I need to add the main car 1 and the auxiliary car 2, then specify the driving routes of car 1 and car 2, and issue an early warning message before the rear-end collision (by calculating the distance between the two vehicles, Judging the distance, if it is too close, an early warning message will be issued)
  Is this set on the carla side? How is this feasible? Can you give me some code ideas and guidance?

**Comment by CCBest2022** [comment]
**another error**
I run manual_control.py according to the process, the following error will appear
![截图 2023-09-02 17-43-15](https://github.com/MaisJamal/carla_apollo_bridge/assets/128120629/2cb9213c-c368-4cb8-a7af-d03c33c71834)

**Comment by CCBest2022** [comment]
> **a new error**
> 
> 1. After I ran successfully according to the bridge project, my dreamview suddenly had an error. I also encountered it once before, and then I solved it by deleting apollo, reinstalling and compiling. But now the problem arises again.
> 2. Through cyber_monitor, you can find that other modules in apollo are normal and have data flowing.
> 
> **![截图 2023-09-02 13-10-26](https://user-images.githubusercontent.com/128120629/265184146-099baef9-42ad-4728-81cf-a06f218a372d.png)**
> 
On dreamview, after I switch from town3 to town4, this error occurs and cannot be fixed.
I'm guessing it's an error caused by missing town4 map files.

**Comment by CCBest2022** [comment]
> > **a new error**
> > 
> > 1. After I ran successfully according to the bridge project, my dreamview suddenly had an error. I also encountered it once before, and then I solved it by deleting apollo, reinstalling and compiling. But now the problem arises again.
> > 2. Through cyber_monitor, you can find that other modules in apollo are normal and have data flowing.
> > 
> > **![截图 2023-09-02 13-10-26](https://user-images.githubusercontent.com/128120629/265184146-099baef9-42ad-4728-81cf-a06f218a372d.png)**
> 
> On dreamview, after I switch from town3 to town4, this error occurs and cannot be fixed. I'm guessing it's an error caused by missing town4 map files.

**I have solved this problem.**
After I delete the town4 file, dreamview can be opened normally.

**Comment by MaisJamal** [comment]
Hello,
Regarding your first question, in Carla there is collision checker which will show if there is a collision, it appears on the simulation window, maybe you can check the code behind it. Another way is to use scenario runner to create the scenario you want and check the distance at each run cycle. Scenario runner has a similar scenario where the obstacle and the ego are about to meet on intersection and the obstacle checks the distance and stops when it's near the ego vehicle. The script is named like this :scenario_runner.py --scenario NoSignalJunctionCrossing 

Regarding the error you faced, it is related to Carla simulator, caused by a previous run that hasn't been properly terminated, please check this issue [#722](https://github.com/carla-simulator/scenario_runner/issues/722#issue-796118682)

**Comment by CCBest2022** [comment]
Thank you very much for your help, I solved the error, I will keep trying.
