### ISSUE TITLE
About the performance of the control module in co-imulation.

### ISSUE THREAD

**Issue by PhilWallace** [MaisJamal/carla_apollo_bridge#6]
Hi there, many thanks for your great work!

I'm also currently testing the Apollo + Carla simulation, according to https://github.com/guardstrikelab/carla_apollo_bridge. However, I met a bunch of control problems, making my vehicle unable to following the routine.

For example, the car cannot accelerate as planned:

![Screenshot from 2023-06-09 01-58-23](https://github.com/MaisJamal/carla_apollo_bridge/assets/37956889/476fb9a6-dd7d-48a2-afb8-886302d7e772)

and many other problems, such as over shoot at turns, the shaggy control... I tried to use the [control_conf.pb.txt](https://github.com/MaisJamal/carla_apollo_bridge/blob/main/apollo_control/control_conf.pb.txt) you provided, but still not very effective.

May I ask whether you have encountered similar problems? How does your car perform in simulation? Many thanks!

BTW, I found one model mismatch problem between Carla and Apollo (Carla generates Tesla Model 3 while Apollo use LinColn2017). Maybe this is helpful for you: https://github.com/guardstrikelab/carla_apollo_bridge/issues/110.

**Comment by MaisJamal** [comment]
Hi, sorry for the late reply.
In the Guardstrike bridge there is indeed a problem with control, the used model of the vehicle in their bridge is Tesla while in Apollo it's Lincoln as you mentioned. 
I am using my Carla/apollo bridge, for which I have tuned the control parameters in Apollo's control module (calibration table). Also in Carla , I have modified a little the car physics to enhance the brake deceleration in control. You can find them in manual_control py.
That's why I recommend using my bridge as well as updating control_conf.pb.txt file in Apollo.
Here are some example graphs that show how well control works with my bridge:

![Screenshot from 2023-06-21 14-57-20](https://github.com/MaisJamal/carla_apollo_bridge/assets/17913075/5930b89c-9a49-4e2b-8fa0-96cbdffa333e)

![Screenshot from 2023-06-21 14-57-14](https://github.com/MaisJamal/carla_apollo_bridge/assets/17913075/29a95cc3-86b4-4874-b8e4-0d5ca2204fc0)

![Screenshot from 2023-06-21 14-56-58](https://github.com/MaisJamal/carla_apollo_bridge/assets/17913075/a94175c5-a8e8-41ae-b31b-8151e30b31d8)

**Comment by PhilWallace** [comment]
> Hi, sorry for the late reply. In the Guardstrike bridge there is indeed a problem with control, the used model of the vehicle in their bridge is Tesla while in Apollo it's Lincoln as you mentioned. I am using my Carla/apollo bridge, for which I have tuned the control parameters in Apollo's control module (calibration table). Also in Carla , I have modified a little the car physics to enhance the brake deceleration in control. You can find them in manual_control py. That's why I recommend using my bridge as well as updating control_conf.pb.txt file in Apollo. Here are some example graphs that show how well control works with my bridge:
> 
> ![Screenshot from 2023-06-21 14-57-20](https://user-images.githubusercontent.com/17913075/247541700-5930b89c-9a49-4e2b-8fa0-96cbdffa333e.png)
> 
> ![Screenshot from 2023-06-21 14-57-14](https://user-images.githubusercontent.com/17913075/247541711-29a95cc3-86b4-4874-b8e4-0d5ca2204fc0.png)
> 
> ![Screenshot from 2023-06-21 14-56-58](https://user-images.githubusercontent.com/17913075/247541728-a94175c5-a8e8-41ae-b31b-8151e30b31d8.png)

Many thanks to your reply! Actually I have also modified the control configuration file, and also the bridge code, and then my car moves better but still not good enough. I will look into your code accordingly. Thanks again.
